/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2025.InterfazGrafica;

import Proyecto2025.CapaPersistencia.PersistenciaApp;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

import javax.swing.table.DefaultTableModel;
import proyecto2025.CapaLogica.FachadaLogica;

/**
 *
 * @author USUARIO
 */
public class PantallaInformacion extends javax.swing.JFrame {
    // Clase que representa la ventana de información de profesores y licencias.
    // Extiende JFrame, por lo que es una ventana gráfica de Swing.

    private int controlError;
    // Variable usada para controlar estados o errores internos de la ventana.

    private void cargarDatosDesdeBD() {
        controlError = -1;
        try {
            ResultSet rs = FachadaLogica.obtenerDatosInformacion();
            // Llama a la fachada lógica para obtener los datos desde la base de datos.

            DefaultTableModel modelo = (DefaultTableModel) tablainfo.getModel();
            modelo.setRowCount(0); // Limpia filas previas de la tabla.

            while (rs.next()) {
                Object[] fila = {
                    rs.getString("nombre"),
                    rs.getString("apellido"),
                    rs.getString("materias"),
                    rs.getString("nombre_grupo"),
                    rs.getInt("id_grupo"),
                    rs.getString("fecha_inicio"),
                    rs.getString("fecha_cierre")
                };
                modelo.addRow(fila);
                // Añade cada fila del ResultSet a la tabla.
            }

            rs.close(); // Cierra el ResultSet.
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
            // Muestra un mensaje de error si ocurre algún problema al cargar datos.
        }
    }

    public PantallaInformacion() {
        controlError = 1;

        initComponents(); // Inicializa los componentes generados por NetBeans.
        cargarDatosDesdeBD(); // Carga datos desde la base de datos al abrir la ventana.

        setDefaultCloseOperation(0); // Evita que cerrar la ventana termine la aplicación.
        setLocationRelativeTo(null); // Centra la ventana en la pantalla.
        setResizable(false); // Bloquea cambios de tamaño.

        tablainfo.setDefaultEditor(Object.class, null); 
        // Deshabilita la edición de celdas de la tabla.

        // Ajusta el alto de la tabla según la cantidad de filas.
        int rowCount = tablainfo.getRowCount();
        int rowHeight = tablainfo.getRowHeight();
        int tableHeight = rowCount * rowHeight;
        tablainfo.setPreferredScrollableViewportSize(new java.awt.Dimension(
            tablainfo.getPreferredSize().width,
            tableHeight
        ));
        tablainfo.revalidate(); // Redibuja la tabla.
        tablainfo.repaint();
    }

    public void agregarFilaATabla(String nombre, String apellido, String materias, String nombre_grupo, int id_grupo,
                                  String fecha_inicio, String fecha_fin) {
        DefaultTableModel modelo = (DefaultTableModel) tablainfo.getModel();
        modelo.addRow(new Object[]{nombre, apellido, materias, nombre_grupo, id_grupo, fecha_inicio, fecha_fin});
        // Permite agregar una fila manualmente a la tabla.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablainfo = new javax.swing.JTable();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablainfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Materias", "Grupo", "id_grupo", "Desde", "Hasta"
            }
        ));
        jScrollPane1.setViewportView(tablainfo);
        if (tablainfo.getColumnModel().getColumnCount() > 0) {
            tablainfo.getColumnModel().getColumn(4).setResizable(false);
        }

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volver)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volver)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
 
        controlError = 2;
        setVisible(false); // Oculta esta ventana.
        PantallaPrincipal principal = new PantallaPrincipal();
        principal.setVisible(true); // Muestra el menú principal.
    

        
// TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablainfo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}

