/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2025.InterfazGrafica;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */

public class PantallaPrincipal extends javax.swing.JFrame {
    // Clase que representa la ventana principal de la aplicación.
    // Desde aquí el usuario puede acceder a las diferentes secciones (registro, información, administración).

    private String usuario;
    // Almacena el nombre del usuario actual (opcional, según flujo de la app).

    // Instancias únicas de las ventanas secundarias
    private PantallaRegistro registroWindow;
    private PantallaInformacion infoWindow;
    private PantallaInformacionAdministracion adminWindow;
    // Se guardan referencias a las ventanas secundarias para poder reutilizarlas
    // sin crear nuevas instancias cada vez que se abren.

    // Getters públicos para acceder a las ventanas secundarias desde otras clases
    public PantallaRegistro getRegistroWindow() {
        return registroWindow;
    }

    public PantallaInformacion getInfoWindow() {
        return infoWindow;
    }

    public PantallaInformacionAdministracion getAdminWindow() {
        return adminWindow;
    }

    public PantallaPrincipal() {
        initComponents();
        // Inicializa todos los componentes gráficos generados por NetBeans

        setResizable(false);
        // Evita que el usuario cambie el tamaño de la ventana

        setLocationRelativeTo(null);
        // Centra la ventana en la pantalla

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // Se evita que cerrar la ventana finalice la aplicación automáticamente
        // para poder manejar el cierre de manera controlada (por ejemplo, confirmación de salida)
    }



    @SuppressWarnings("unchecked")
   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        ingresar = new javax.swing.JMenu();
        registro = new javax.swing.JMenuItem();
        informacion = new javax.swing.JMenuItem();
        infoadm = new javax.swing.JMenuItem();
        Cierre = new javax.swing.JMenu();
        cerrar = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ingresar.setText("Ingresar");

        registro.setText("Registro");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        ingresar.add(registro);

        informacion.setText("informacion ");
        informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionActionPerformed(evt);
            }
        });
        ingresar.add(informacion);

        infoadm.setText("Informacion administracion");
        infoadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoadmActionPerformed(evt);
            }
        });
        ingresar.add(infoadm);

        jMenuBar1.add(ingresar);

        Cierre.setText("Cerrar");

        cerrar.setText("cerrar ventana");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        Cierre.add(cerrar);

        jMenuBar1.add(Cierre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  private boolean accesoPermitido() {
    PantallaLogin loginDialog = new PantallaLogin(this); // pasa la ventana principal
    loginDialog.setVisible(true); // se bloquea hasta que se cierre el login
    return loginDialog.isLoginExitoso(); // devuelve true si el login fue exitoso
}


    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed

        // TODO add your handling code here:
        
     System.exit(0);//APaga y cierra la app completamente

        

    }//GEN-LAST:event_cerrarActionPerformed

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
  // Cierra u oculta la ventana principal
    this.setVisible(false); 

    // Si no existe la ventana de registro, crearla
    if (registroWindow == null) {
        registroWindow = new PantallaRegistro("defecto");
    }

    // Mostrar la ventana de registro
    registroWindow.setVisible(true);

    }//GEN-LAST:event_registroActionPerformed

    private void informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionActionPerformed
                                             
    // Crear la ventana solo si no existe
    if (infoWindow == null) {
        infoWindow = new PantallaInformacion();
    }

    // Mostrar la ventana
    infoWindow.setVisible(true);

    // Ocultar la ventana principal
    this.setVisible(false);

    }//GEN-LAST:event_informacionActionPerformed

    private void infoadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoadmActionPerformed
      // Método que se ejecuta al hacer clic en el botón o acción asociada a "Información Administración".
    // Su objetivo es abrir el diálogo de login antes de mostrar la ventana de administración.

    PantallaLogin loginDialog = new PantallaLogin(this);
    // Crea un nuevo diálogo de login, pasando 'this' como ventana padre para centrarlo.

    loginDialog.setVisible(true);
    // Muestra el diálogo de login de forma modal.
    // La ejecución de este método se detiene hasta que el usuario cierre el diálogo.

    dispose();
    // Cierra la ventana actual de PantallaPrincipal.
    // Esto asegura que al iniciar sesión, la ventana principal no quede abierta detrás del login.


    }//GEN-LAST:event_infoadmActionPerformed

     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
        
    
    
    /**
     * @param args the command line arguments
     */
    
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
}
        //</editor-fold>

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cierre;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JMenuItem infoadm;
    private javax.swing.JMenuItem informacion;
    private javax.swing.JMenu ingresar;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem registro;
    // End of variables declaration//GEN-END:variables
}
